module.exports = {
  AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
  ASW_BUCKET_NAME: process.env.ASW_BUCKET_NAME,
  ASW_BUCKET_REGION: process.env.ASW_BUCKET_REGION,
  AWS_CLOUDFRONT: process.env.AWS_CLOUDFRONT,
};
